name: Tests

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        poetry-version: ["1.0", "1.1.15"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

  steps:
  - name: Check out repository code
    uses: actions/checkout@v2

  # Setup Python (faster than using Python container)
  - name: Setup Python
    uses: actions/setup-python@v2
    with:
      python-version: ${{ matrix.python-version }}

  - name: Run image
    uses: abatilo/actions-poetry@v2
    with:
      poetry-version: ${{ matrix.poetry-version }}

  - uses: actions/cache@v3
    name: Define a cache for the virtual environment based on the dependencies lock file
    with:
      path: ./.venv
      key: venv-${{ hashFiles('poetry.lock') }}
  - name: Install the project dependencies
    run: poetry install
    - name: Run the automated tests (for example)
      run: poetry run pytest -v
