name: Tests

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.6.1"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}  
    - name: Install dependencies via Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Run the automated tests
      run: poetry run pytest -v
